[features]
seeds = false
skip-lint = false
[programs.devnet]
betting_game = "9PyH3wLrcfjjCFqMRq5mMapnqs6qb38Vx5XTTRgM3C9Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
